# Generated by Django 4.2.5 on 2023-10-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='name',
            field=models.CharField(default='PAGAMENTO', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='payment',
            name='unit',
            field=models.CharField(default='und', max_length=4),
        ),
    ]
