# Generated by Django 4.2.5 on 2023-10-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0005_alter_payment_createddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
